<?php
return ['messages'=>['Contact'=>'Contact','Datum Do'=>'Дата по','Datum Od'=>'Дата с','Email'=>'Email','First Choice'=>'First Choice','Hidden Field'=>'Hidden Field','Ime'=>'Имя','Ime i Prezime'=>'Имя и фамилия','Izaberi Auto'=>'Выберите автомобиль','Message'=>'Текст','New submission from {form_title}'=>'New submission from {form_title}','Poruka'=>'Сообщение','Pošalji'=>'Отправить','Prezime'=>'Фамилия','Second Choice'=>'Second Choice','Telefon'=>'Телефон','Thanks for contacting us! We will get in touch with you shortly.
<img class="alignnone size-full wp-image-407" src="http://localhost:8080/forza-rent/wp-content/uploads/2025/12/cropped-logo-6.png" alt="" width="131" height="25" />

<a class="gf-confirm-btn" href="/forza-rent/">Back home</a>'=>'Thanks for contacting us! We will get in touch with you shortly. 
<img class="alignnone size-full wp-image-407" src="http://localhost:8080/forza-rent/wp-content/uploads/2025/12/cropped-logo-6.png" alt="" width="131" height="25">

<a class="gf-confirm-btn" href="/forza-rent/ru/">Назад на главную</a>','Third Choice'=>'Third Choice','email-4-placeholder'=>'example@example.com','example@example.com'=>'example@example.com','field-1-label'=>'Имя и фамилия','field-10-label'=>'Выберите автомобиль','field-11-label'=>'Дата с','field-12-label'=>'Дата по','field-14-defaultValue'=>'{embed_post:post_title}','field-14-label'=>'Hidden Field','field-4-label'=>'Email','field-5-label'=>'Сообщение','field-6-label'=>'Телефон','field-confirmation-message_Default-Confirmation'=>'Thanks for contacting us! We will get in touch with you shortly. 
<img class="alignnone size-full wp-image-407" src="http://localhost:8080/forza-rent/wp-content/uploads/2025/12/cropped-logo-6.png" alt="" width="131" height="25">

<a class="gf-confirm-btn" href="/forza-rent/ru/">Назад на главную</a>','field-notification-message_Admin-Notification'=>'{all_fields}','form_submit_button'=>'Отправить','form_title'=>'Contact','name-1-customLabel-input-1.3'=>'Имя','name-1-customLabel-input-1.6'=>'Фамилия','notification-subject_Admin-Notification'=>'New submission from {form_title}','select-10-choice-0-First-Choice'=>'First Choice','select-10-choice-0-First-Choice-value'=>'First Choice','select-10-choice-1-Second-Choice'=>'Second Choice','select-10-choice-1-Second-Choice-value'=>'Second Choice','select-10-choice-2-Third-Choice'=>'Third Choice','select-10-choice-2-Third-Choice-value'=>'Third Choice','textarea-5-placeholder'=>'Текст','{all_fields}'=>'{all_fields}','{embed_post:post_title}'=>'{embed_post:post_title}']];
