<?php
return ['messages'=>['Contact'=>'Contact','Datum Do'=>'Date To','Datum Od'=>'Date From','Email'=>'Email','First Choice'=>'First Choice','Hidden Field'=>'Hidden Field','Ime'=>'First name','Ime i Prezime'=>'Full name','Izaberi Auto'=>'Chose vehicle','Message'=>'Text','New submission from {form_title}'=>'New submission from {form_title}','Poruka'=>'Message','Pošalji'=>'Send','Prezime'=>'Last name','Second Choice'=>'Second Choice','Telefon'=>'Phone','Thanks for contacting us! We will get in touch with you shortly.
<img class="alignnone size-full wp-image-407" src="http://localhost:8080/forza-rent/wp-content/uploads/2025/12/cropped-logo-6.png" alt="" width="131" height="25" />

<a class="gf-confirm-btn" href="/forza-rent/">Back home</a>'=>'Thanks for contacting us! We will get in touch with you shortly. 
<img class="alignnone size-full wp-image-407" src="http://localhost:8080/forza-rent/wp-content/uploads/2025/12/cropped-logo-6.png" alt="" width="131" height="25">

<a class="gf-confirm-btn" href="/forza-rent/">Back home</a>','Third Choice'=>'Third Choice','email-4-placeholder'=>'example@example.com','example@example.com'=>'example@example.com','field-1-label'=>'Full name','field-10-label'=>'Chose vehicle','field-11-label'=>'Date From','field-12-label'=>'Date To','field-14-defaultValue'=>'{embed_post:post_title}','field-14-label'=>'Hidden Field','field-4-label'=>'Email','field-5-label'=>'Message','field-6-label'=>'Phone','field-confirmation-message_Default-Confirmation'=>'Thanks for contacting us! We will get in touch with you shortly. 
<img class="alignnone size-full wp-image-407" src="http://localhost:8080/forza-rent/wp-content/uploads/2025/12/cropped-logo-6.png" alt="" width="131" height="25">

<a class="gf-confirm-btn" href="/forza-rent/">Back home</a>','field-notification-message_Admin-Notification'=>'{all_fields}','form_submit_button'=>'Send','form_title'=>'Contact','name-1-customLabel-input-1.3'=>'First name','name-1-customLabel-input-1.6'=>'Last name','notification-subject_Admin-Notification'=>'New submission from {form_title}','select-10-choice-0-First-Choice'=>'First Choice','select-10-choice-0-First-Choice-value'=>'First Choice','select-10-choice-1-Second-Choice'=>'Second Choice','select-10-choice-1-Second-Choice-value'=>'Second Choice','select-10-choice-2-Third-Choice'=>'Third Choice','select-10-choice-2-Third-Choice-value'=>'Third Choice','textarea-5-placeholder'=>'Text','{all_fields}'=>'{all_fields}','{embed_post:post_title}'=>'{embed_post:post_title}']];
